version: "3.5"


networks:
    frontend:
        driver: 'bridge'
    backend:
        driver: 'bridge'


services:
    app:
        build:
            context: .
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/app
        networks:
            - frontend
            - backend
        depends_on:
            - redis
            - mysql
    ### MySQL ################################################
    mysql:
        image: mysql:latest
        environment:
            - MYSQL_DATABASE=default
            - MYSQL_USER=default
            - MYSQL_PASSWORD=default
            - MYSQL_ROOT_PASSWORD=root
            - TZ=UTC
        volumes:
            - ./docker/database/mysql:/var/lib/mysql
            - ./docker/database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
        networks:
            - backend
    ### Redis ################################################
    redis:
        image: redis:latest
        volumes:
            - ./docker/database/redis:/data
        command: --requirepass redis
        ports:
            - "6379:6379"
        networks:
            - backend


